name: Unfolding
favicon: null
layout_spectrum: 0.9451083808671683
typography_spectrum: 0.9322258410975337
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.727953142952174
  lightness: 0.109458580147475
  saturation: 0.2064680599141866
  rhythmicContrast: 0.7960680113174021
purpose: []
